"use client";

import type { Playbook } from "@/lib/types";
import { StrategyCard } from "./StrategyCard";

export function OperationalPlaybook({
  playbook,
  selectedId,
  onSelect,
  source,
}: {
  playbook: Playbook;
  selectedId: string;
  onSelect: (id: string) => void;
  source?: "ai" | "rules";
}) {
  return (
    <div className="surface-panel p-5">
      <div className="flex items-center justify-between mb-3">
        <div className="text-xs muted uppercase tracking-wide flex items-center gap-2">
          Management strategies ({playbook.strategies.length})
          {source && (
            <span
              className="text-[10px] px-1.5 py-0.5 rounded-full font-medium normal-case"
              style={{
                background: "var(--panel-2)",
                color: source === "ai" ? "var(--accent)" : "var(--muted)",
              }}
              title={
                source === "ai"
                  ? "Generated by an LLM (Groq/Llama) grounded on the trained forecast + ASTraM historical statistics"
                  : "Generated by the deterministic rule engine (AI key not set or call failed)"
              }
            >
              {source === "ai" ? "✨ AI-generated" : "⚙ rule-based"}
            </span>
          )}
        </div>
        <div className="text-[11px] muted">click to inspect</div>
      </div>
      <div className="grid grid-cols-1 gap-3">
        {playbook.strategies.map((s) => (
          <StrategyCard
            key={s.id}
            strategy={s}
            selected={selectedId === s.id}
            onSelect={() => onSelect(s.id)}
          />
        ))}
      </div>
    </div>
  );
}
