// GridSense — Historical Precedent Engine.
//
// Given a planned/forecast event, retrieve genuinely similar PAST events from the
// ASTraM corpus and report their *actual* outcomes (real clearance times, closure
// rates, severity mix). This grounds the model forecast in empirical precedent and
// gives an honest uncertainty band (P50/P90 from real analogs) without training a
// separate quantile model.
//
// Data: src/data/precedents.json — ~2,777 resolved events with actual_duration_min,
// generated by ml/prepare.py (precedents()). Fully self-contained on Vercel.

import precedentsData from "@/data/precedents.json";
import type { EventInput } from "@/lib/gridsense";

export type Precedent = {
  id: string;
  cause: string;
  corridor: string;
  zone: string | null;
  lat: number;
  lon: number;
  requires_road_closure: number; // 0 | 1
  is_peak: number; // 0 | 1
  is_planned: number; // 0 | 1
  priority: string;
  actual_duration_min: number;
  tier: string;
  impact_score: number;
  start_date: string | null;
};

const PRECEDENTS = precedentsData as Precedent[];

// Similarity weights (sum = 1.0). Cause dominates — a breakdown and a protest are
// operationally different events even on the same road.
const W = {
  cause: 0.45,
  corridor: 0.2,
  closure: 0.12,
  peak: 0.08,
  geo: 0.15,
} as const;

// Beyond this distance the geo term contributes ~nothing.
const GEO_FALLOFF_KM = 12;

function haversineKm(aLat: number, aLon: number, bLat: number, bLon: number): number {
  const R = 6371;
  const dLat = ((bLat - aLat) * Math.PI) / 180;
  const dLon = ((bLon - aLon) * Math.PI) / 180;
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((aLat * Math.PI) / 180) *
      Math.cos((bLat * Math.PI) / 180) *
      Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(s)));
}

function similarity(inp: EventInput, p: Precedent): number {
  let score = 0;
  if (p.cause === inp.cause) score += W.cause;
  if (p.corridor === inp.corridor) score += W.corridor;
  if (p.requires_road_closure === (inp.requires_road_closure ? 1 : 0)) score += W.closure;
  if (p.is_peak === (inp.is_peak ? 1 : 0)) score += W.peak;
  if (inp.lat != null && inp.lon != null) {
    const km = haversineKm(inp.lat, inp.lon, p.lat, p.lon);
    score += W.geo * Math.max(0, 1 - km / GEO_FALLOFF_KM);
  }
  return score;
}

function quantile(sorted: number[], q: number): number {
  if (!sorted.length) return 0;
  const pos = (sorted.length - 1) * q;
  const lo = Math.floor(pos);
  const hi = Math.ceil(pos);
  if (lo === hi) return sorted[lo];
  return sorted[lo] + (sorted[hi] - sorted[lo]) * (pos - lo);
}

export type PrecedentMatch = Precedent & { similarity: number; distance_km: number | null };

export type PrecedentSummary = {
  n: number;
  same_cause_n: number;
  median_clearance_min: number; // P50 of actual durations
  p90_clearance_min: number;
  min_clearance_min: number;
  max_clearance_min: number;
  closure_rate: number; // share of analogs that needed a road closure
  tier_mix: Record<string, number>; // count by tier among analogs
  forecast_within_band: boolean | null; // is the model forecast inside [P25, P90]?
  matches: PrecedentMatch[]; // top representative analogs (for UI)
};

// Find the k most similar past events and summarize their real outcomes.
// `forecastDurationMin` (optional) lets us flag whether the model estimate sits
// inside the empirical spread of precedent.
export function findSimilarEvents(
  inp: EventInput,
  k = 15,
  forecastDurationMin?: number
): PrecedentSummary {
  const ranked = PRECEDENTS.map((p) => ({
    ...p,
    similarity: similarity(inp, p),
    distance_km:
      inp.lat != null && inp.lon != null
        ? Math.round(haversineKm(inp.lat, inp.lon, p.lat, p.lon) * 10) / 10
        : null,
  }))
    .filter((p) => p.similarity > 0)
    .sort((a, b) => b.similarity - a.similarity);

  const top = ranked.slice(0, k);
  const durations = top.map((p) => p.actual_duration_min).sort((a, b) => a - b);

  const tier_mix: Record<string, number> = {};
  for (const p of top) tier_mix[p.tier] = (tier_mix[p.tier] ?? 0) + 1;

  const p50 = quantile(durations, 0.5);
  const p90 = quantile(durations, 0.9);
  const p25 = quantile(durations, 0.25);

  const round1 = (n: number) => Math.round(n * 10) / 10;

  return {
    n: top.length,
    same_cause_n: top.filter((p) => p.cause === inp.cause).length,
    median_clearance_min: round1(p50),
    p90_clearance_min: round1(p90),
    min_clearance_min: round1(durations[0] ?? 0),
    max_clearance_min: round1(durations[durations.length - 1] ?? 0),
    closure_rate:
      top.length ? Math.round((top.filter((p) => p.requires_road_closure).length / top.length) * 100) / 100 : 0,
    tier_mix,
    forecast_within_band:
      forecastDurationMin == null
        ? null
        : forecastDurationMin >= p25 && forecastDurationMin <= p90,
    // A handful of representative analogs for the UI (closest first).
    matches: top.slice(0, 6),
  };
}
